name: CI native

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  native-build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
      options: --entrypoint ""

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Main build
      run: ./gradlew build -x test -Dquarkus.package.type=native -Dquarkus.native.native-image-xmx=4g -i

    - name: Prepare tags
      id: docker_tags
      run: echo "::set-output name=docker_tags::latest,$(ls build/es-web-analytics-*-runner | cut -d'-' -f4)"

    - name: Docker build and push
      uses: docker/build-push-action@v1
      with:
        username: soufianesakhi
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: soufianesakhi/es-web-analytics
        dockerfile: docker/Dockerfile.native
        tags: ${{ steps.docker_tags.outputs.docker_tags }}
