name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'docker/Dockerfile'
      - '**.kts'
      - '**.properties'
    branches: [ master ]
  pull_request:
    paths:
      - 'src/**'
      - 'docker/Dockerfile'
      - '**.kts'
      - '**.properties'
    branches: [ master ]

jobs:
  jvm-build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:14-jdk-alpine

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Main build
      run: ./gradlew build -x test -i

    - name: Prepare tags
      id: docker_tags
      run: echo "::set-output name=docker_tags::latest,$(ls build/es-web-analytics-*.jar | cut -d'-' -f4)"

    - name: Docker build and push
      uses: docker/build-push-action@v1
      with:
        username: soufianesakhi
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: soufianesakhi/es-web-analytics-jvm
        dockerfile: docker/Dockerfile
        tags: ${{ steps.docker_tags.outputs.docker_tags }}
